{
  "unet_type": "marigold",
  "unet_id": "prs-eth/marigold-depth-v1-1",
  "vae_mode": "tiny",
  "enable_progress_bar": true,
  "data_root": "../radarhd_dataset/",
  "validation_split": 0.1,
  "num_workers": 2,
  "use_fp16": true,
  "find_unused_parameters": false,
  "device": "auto",
  "num_epochs": 200,
  "learning_rate": 0.0001,
  "batch_size": 16,
  "gradient_accumulation_steps": 1,
  "max_grad_norm": 1.0,
  "output_dir": "./results",
  "adam_beta1": 0.9,
  "adam_beta2": 0.999,
  "adam_weight_decay": 0.01,
  "adam_epsilon": 1e-08,
  "noise_scheduler_id": "DDPMScheduler",
  "num_train_timesteps": 500,
  "num_inference_steps": 50,
  "beta_start": 0.00085,
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "prediction_type": "epsilon",
  "use_perceptual_loss": true,
  "loss_weight_l1": 1.0,
  "loss_weight_ssim": 0.5,
  "loss_weight_lpips": 0.5,
  "num_samples": 4
}
